// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Box: typeof import('./components/ui/utils/box.vue')['default']
    Btn: typeof import('./components/ui/btns/Btn.vue')['default']
    BtnAdd: typeof import('./components/ui/btns/BtnAdd.vue')['default']
    BtnBack: typeof import('./components/ui/btns/BtnBack.vue')['default']
    BtnCancel: typeof import('./components/ui/btns/BtnCancel.vue')['default']
    BtnClose: typeof import('./components/ui/btns/BtnClose.vue')['default']
    BtnDelete: typeof import('./components/ui/btns/BtnDelete.vue')['default']
    BtnForward: typeof import('./components/ui/btns/BtnForward.vue')['default']
    BtnMenu: typeof import('./components/ui/btns/BtnMenu.vue')['default']
    BtnSave: typeof import('./components/ui/btns/BtnSave.vue')['default']
    CheckBox: typeof import('./components/ui/forms/CheckBox.vue')['default']
    Chip: typeof import('./components/ui/utils/Chip.vue')['default']
    FilePicker: typeof import('./components/ui/forms/FilePicker.vue')['default']
    HomeTabs: typeof import('./components/HomeTabs.vue')['default']
    Icon: typeof import('./components/ui/utils/Icon.vue')['default']
    IntegerField: typeof import('./components/ui/forms/IntegerField.vue')['default']
    Item: typeof import('./components/ui/lists/Item.vue')['default']
    ItemSection: typeof import('./components/ui/lists/ItemSection.vue')['default']
    ItemSectionLabel: typeof import('./components/ui/lists/ItemSectionLabel.vue')['default']
    List: typeof import('./components/ui/lists/List.vue')['default']
    MoneyField: typeof import('./components/ui/forms/MoneyField.vue')['default']
    NotFound: typeof import('./components/NotFound.vue')['default']
    Page: typeof import('./components/ui/pages/Page.vue')['default']
    PageBody: typeof import('./components/ui/pages/PageBody.vue')['default']
    PageFooter: typeof import('./components/ui/pages/PageFooter.vue')['default']
    PageHeader: typeof import('./components/ui/pages/PageHeader.vue')['default']
    PasswordField: typeof import('./components/ui/forms/PasswordField.vue')['default']
    PhoneField: typeof import('./components/ui/forms/PhoneField.vue')['default']
    SearchField: typeof import('./components/ui/forms/SearchField.vue')['default']
    SelectField: typeof import('./components/ui/forms/SelectField.vue')['default']
    SelectText: typeof import('./components/ui/forms/SelectText.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    TextArea: typeof import('./components/ui/forms/TextArea.vue')['default']
    TextField: typeof import('./components/ui/forms/TextField.vue')['default']
    TextLabel: typeof import('./components/ui/forms/TextLabel.vue')['default']
    ToggleField: typeof import('./components/ui/forms/ToggleField.vue')['default']
  }
}

export { }
